#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

NAME=happ-openwrt
PROG=/usr/bin/happ-openwrt

start_service() {
	config_load happ-openwrt
	config_get_bool enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	$PROG -config /etc/config/happ-openwrt update || return 1
	/etc/init.d/sing-box enable >/dev/null 2>&1
	/etc/init.d/sing-box start >/dev/null 2>&1
}

stop_service() {
	/etc/init.d/sing-box stop >/dev/null 2>&1
}

reload_service() {
	update_subscription
}

restart() {
	stop
	start
}

update_subscription() {
	$PROG -config /etc/config/happ-openwrt -restart update-subscription
}

boot() {
	start
}
